package com.mxxk.lightdream.entity;

/**
 * DicBaseEntity
 *
 * @auther zhang
 * @date 2020/6/4
 **/
public class ShareNature {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_area.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_area.code
     *
     * @mbggenerated
     */
    private String keyCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_area.name_zh
     *
     * @mbggenerated
     */
    private String nameCn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_area.name_en
     *
     * @mbggenerated
     */
    private String nameEn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_area.name_jp
     *
     * @mbggenerated
     */
    private String nameJp;


    private Long orderNum;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getKeyCode() {
        return keyCode;
    }

    public void setKeyCode(String keyCode) {
        this.keyCode = keyCode;
    }

    public String getNameCn() {
        return nameCn;
    }

    public void setNameCn(String nameCn) {
        this.nameCn = nameCn;
    }

    public String getNameEn() {
        return nameEn;
    }

    public void setNameEn(String nameEn) {
        this.nameEn = nameEn;
    }

    public String getNameJp() {
        return nameJp;
    }

    public void setNameJp(String nameJp) {
        this.nameJp = nameJp;
    }

    public Long getOrderNum() {
        return orderNum;
    }

    public void setOrderNum(Long orderNum) {
        this.orderNum = orderNum;
    }
}
