package com.mxxk.lightdream.entity;

public class TradeData {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_data.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_data.stock_name
     *
     * @mbggenerated
     */
    private String stockName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_data.stock_code
     *
     * @mbggenerated
     */
    private String stockCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_data.newest_price
     *
     * @mbggenerated
     */
    private Double newestPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_data.price_change
     *
     * @mbggenerated
     */
    private Double priceChange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_data.price_change_range
     *
     * @mbggenerated
     */
    private String priceChangeRange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_data.stock_date
     *
     * @mbggenerated
     */
    private String stockDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_data.start_price
     *
     * @mbggenerated
     */
    private Double startPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_data.max_price
     *
     * @mbggenerated
     */
    private Double maxPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_data.amplitude
     *
     * @mbggenerated
     */
    private String amplitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_data.change_hands
     *
     * @mbggenerated
     */
    private String changeHands;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_data.yes_price
     *
     * @mbggenerated
     */
    private Double yesPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_data.min_price
     *
     * @mbggenerated
     */
    private Double minPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_data.trade_hands
     *
     * @mbggenerated
     */
    private String tradeHands;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_data.trade_sum_money
     *
     * @mbggenerated
     */
    private String tradeSumMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_data.volume_ratio
     *
     * @mbggenerated
     */
    private Double volumeRatio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_data.pe_ratio_after_deduction
     *
     * @mbggenerated
     */
    private Double peRatioAfterDeduction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_data.pe_ratio
     *
     * @mbggenerated
     */
    private Double peRatio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_data.pb_ratio
     *
     * @mbggenerated
     */
    private Double pbRatio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_data.earnings_per_share
     *
     * @mbggenerated
     */
    private String earningsPerShare;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_data.industry
     *
     * @mbggenerated
     */
    private String industry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_data.avg_pe_ratio
     *
     * @mbggenerated
     */
    private Double avgPeRatio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_data.avg_pe_ratio_after_deduction
     *
     * @mbggenerated
     */
    private Double avgPeRatioAfterDeduction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_data.important_info
     *
     * @mbggenerated
     */
    private String importantInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_data.total_stocks
     *
     * @mbggenerated
     */
    private String totalStocks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_data.circulate_stocks
     *
     * @mbggenerated
     */
    private String circulateStocks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_data.data
     *
     * @mbggenerated
     */
    private byte[] data;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_data.id
     *
     * @return the value of trade_data.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_data.id
     *
     * @param id the value for trade_data.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_data.stock_name
     *
     * @return the value of trade_data.stock_name
     *
     * @mbggenerated
     */
    public String getStockName() {
        return stockName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_data.stock_name
     *
     * @param stockName the value for trade_data.stock_name
     *
     * @mbggenerated
     */
    public void setStockName(String stockName) {
        this.stockName = stockName == null ? null : stockName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_data.stock_code
     *
     * @return the value of trade_data.stock_code
     *
     * @mbggenerated
     */
    public String getStockCode() {
        return stockCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_data.stock_code
     *
     * @param stockCode the value for trade_data.stock_code
     *
     * @mbggenerated
     */
    public void setStockCode(String stockCode) {
        this.stockCode = stockCode == null ? null : stockCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_data.newest_price
     *
     * @return the value of trade_data.newest_price
     *
     * @mbggenerated
     */
    public Double getNewestPrice() {
        return newestPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_data.newest_price
     *
     * @param newestPrice the value for trade_data.newest_price
     *
     * @mbggenerated
     */
    public void setNewestPrice(Double newestPrice) {
        this.newestPrice = newestPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_data.price_change
     *
     * @return the value of trade_data.price_change
     *
     * @mbggenerated
     */
    public Double getPriceChange() {
        return priceChange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_data.price_change
     *
     * @param priceChange the value for trade_data.price_change
     *
     * @mbggenerated
     */
    public void setPriceChange(Double priceChange) {
        this.priceChange = priceChange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_data.price_change_range
     *
     * @return the value of trade_data.price_change_range
     *
     * @mbggenerated
     */
    public String getPriceChangeRange() {
        return priceChangeRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_data.price_change_range
     *
     * @param priceChangeRange the value for trade_data.price_change_range
     *
     * @mbggenerated
     */
    public void setPriceChangeRange(String priceChangeRange) {
        this.priceChangeRange = priceChangeRange == null ? null : priceChangeRange.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_data.stock_date
     *
     * @return the value of trade_data.stock_date
     *
     * @mbggenerated
     */
    public String getStockDate() {
        return stockDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_data.stock_date
     *
     * @param stockDate the value for trade_data.stock_date
     *
     * @mbggenerated
     */
    public void setStockDate(String stockDate) {
        this.stockDate = stockDate == null ? null : stockDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_data.start_price
     *
     * @return the value of trade_data.start_price
     *
     * @mbggenerated
     */
    public Double getStartPrice() {
        return startPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_data.start_price
     *
     * @param startPrice the value for trade_data.start_price
     *
     * @mbggenerated
     */
    public void setStartPrice(Double startPrice) {
        this.startPrice = startPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_data.max_price
     *
     * @return the value of trade_data.max_price
     *
     * @mbggenerated
     */
    public Double getMaxPrice() {
        return maxPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_data.max_price
     *
     * @param maxPrice the value for trade_data.max_price
     *
     * @mbggenerated
     */
    public void setMaxPrice(Double maxPrice) {
        this.maxPrice = maxPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_data.amplitude
     *
     * @return the value of trade_data.amplitude
     *
     * @mbggenerated
     */
    public String getAmplitude() {
        return amplitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_data.amplitude
     *
     * @param amplitude the value for trade_data.amplitude
     *
     * @mbggenerated
     */
    public void setAmplitude(String amplitude) {
        this.amplitude = amplitude == null ? null : amplitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_data.change_hands
     *
     * @return the value of trade_data.change_hands
     *
     * @mbggenerated
     */
    public String getChangeHands() {
        return changeHands;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_data.change_hands
     *
     * @param changeHands the value for trade_data.change_hands
     *
     * @mbggenerated
     */
    public void setChangeHands(String changeHands) {
        this.changeHands = changeHands == null ? null : changeHands.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_data.yes_price
     *
     * @return the value of trade_data.yes_price
     *
     * @mbggenerated
     */
    public Double getYesPrice() {
        return yesPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_data.yes_price
     *
     * @param yesPrice the value for trade_data.yes_price
     *
     * @mbggenerated
     */
    public void setYesPrice(Double yesPrice) {
        this.yesPrice = yesPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_data.min_price
     *
     * @return the value of trade_data.min_price
     *
     * @mbggenerated
     */
    public Double getMinPrice() {
        return minPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_data.min_price
     *
     * @param minPrice the value for trade_data.min_price
     *
     * @mbggenerated
     */
    public void setMinPrice(Double minPrice) {
        this.minPrice = minPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_data.trade_hands
     *
     * @return the value of trade_data.trade_hands
     *
     * @mbggenerated
     */
    public String getTradeHands() {
        return tradeHands;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_data.trade_hands
     *
     * @param tradeHands the value for trade_data.trade_hands
     *
     * @mbggenerated
     */
    public void setTradeHands(String tradeHands) {
        this.tradeHands = tradeHands == null ? null : tradeHands.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_data.trade_sum_money
     *
     * @return the value of trade_data.trade_sum_money
     *
     * @mbggenerated
     */
    public String getTradeSumMoney() {
        return tradeSumMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_data.trade_sum_money
     *
     * @param tradeSumMoney the value for trade_data.trade_sum_money
     *
     * @mbggenerated
     */
    public void setTradeSumMoney(String tradeSumMoney) {
        this.tradeSumMoney = tradeSumMoney == null ? null : tradeSumMoney.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_data.volume_ratio
     *
     * @return the value of trade_data.volume_ratio
     *
     * @mbggenerated
     */
    public Double getVolumeRatio() {
        return volumeRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_data.volume_ratio
     *
     * @param volumeRatio the value for trade_data.volume_ratio
     *
     * @mbggenerated
     */
    public void setVolumeRatio(Double volumeRatio) {
        this.volumeRatio = volumeRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_data.pe_ratio_after_deduction
     *
     * @return the value of trade_data.pe_ratio_after_deduction
     *
     * @mbggenerated
     */
    public Double getPeRatioAfterDeduction() {
        return peRatioAfterDeduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_data.pe_ratio_after_deduction
     *
     * @param peRatioAfterDeduction the value for trade_data.pe_ratio_after_deduction
     *
     * @mbggenerated
     */
    public void setPeRatioAfterDeduction(Double peRatioAfterDeduction) {
        this.peRatioAfterDeduction = peRatioAfterDeduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_data.pe_ratio
     *
     * @return the value of trade_data.pe_ratio
     *
     * @mbggenerated
     */
    public Double getPeRatio() {
        return peRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_data.pe_ratio
     *
     * @param peRatio the value for trade_data.pe_ratio
     *
     * @mbggenerated
     */
    public void setPeRatio(Double peRatio) {
        this.peRatio = peRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_data.pb_ratio
     *
     * @return the value of trade_data.pb_ratio
     *
     * @mbggenerated
     */
    public Double getPbRatio() {
        return pbRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_data.pb_ratio
     *
     * @param pbRatio the value for trade_data.pb_ratio
     *
     * @mbggenerated
     */
    public void setPbRatio(Double pbRatio) {
        this.pbRatio = pbRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_data.earnings_per_share
     *
     * @return the value of trade_data.earnings_per_share
     *
     * @mbggenerated
     */
    public String getEarningsPerShare() {
        return earningsPerShare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_data.earnings_per_share
     *
     * @param earningsPerShare the value for trade_data.earnings_per_share
     *
     * @mbggenerated
     */
    public void setEarningsPerShare(String earningsPerShare) {
        this.earningsPerShare = earningsPerShare == null ? null : earningsPerShare.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_data.industry
     *
     * @return the value of trade_data.industry
     *
     * @mbggenerated
     */
    public String getIndustry() {
        return industry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_data.industry
     *
     * @param industry the value for trade_data.industry
     *
     * @mbggenerated
     */
    public void setIndustry(String industry) {
        this.industry = industry == null ? null : industry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_data.avg_pe_ratio
     *
     * @return the value of trade_data.avg_pe_ratio
     *
     * @mbggenerated
     */
    public Double getAvgPeRatio() {
        return avgPeRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_data.avg_pe_ratio
     *
     * @param avgPeRatio the value for trade_data.avg_pe_ratio
     *
     * @mbggenerated
     */
    public void setAvgPeRatio(Double avgPeRatio) {
        this.avgPeRatio = avgPeRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_data.avg_pe_ratio_after_deduction
     *
     * @return the value of trade_data.avg_pe_ratio_after_deduction
     *
     * @mbggenerated
     */
    public Double getAvgPeRatioAfterDeduction() {
        return avgPeRatioAfterDeduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_data.avg_pe_ratio_after_deduction
     *
     * @param avgPeRatioAfterDeduction the value for trade_data.avg_pe_ratio_after_deduction
     *
     * @mbggenerated
     */
    public void setAvgPeRatioAfterDeduction(Double avgPeRatioAfterDeduction) {
        this.avgPeRatioAfterDeduction = avgPeRatioAfterDeduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_data.important_info
     *
     * @return the value of trade_data.important_info
     *
     * @mbggenerated
     */
    public String getImportantInfo() {
        return importantInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_data.important_info
     *
     * @param importantInfo the value for trade_data.important_info
     *
     * @mbggenerated
     */
    public void setImportantInfo(String importantInfo) {
        this.importantInfo = importantInfo == null ? null : importantInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_data.total_stocks
     *
     * @return the value of trade_data.total_stocks
     *
     * @mbggenerated
     */
    public String getTotalStocks() {
        return totalStocks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_data.total_stocks
     *
     * @param totalStocks the value for trade_data.total_stocks
     *
     * @mbggenerated
     */
    public void setTotalStocks(String totalStocks) {
        this.totalStocks = totalStocks == null ? null : totalStocks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_data.circulate_stocks
     *
     * @return the value of trade_data.circulate_stocks
     *
     * @mbggenerated
     */
    public String getCirculateStocks() {
        return circulateStocks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_data.circulate_stocks
     *
     * @param circulateStocks the value for trade_data.circulate_stocks
     *
     * @mbggenerated
     */
    public void setCirculateStocks(String circulateStocks) {
        this.circulateStocks = circulateStocks == null ? null : circulateStocks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_data.data
     *
     * @return the value of trade_data.data
     *
     * @mbggenerated
     */
    public byte[] getData() {
        return data;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_data.data
     *
     * @param data the value for trade_data.data
     *
     * @mbggenerated
     */
    public void setData(byte[] data) {
        this.data = data;
    }
}