server:
  port: 8081

spring:
    datasource:
       name: mxxk
       url: jdbc:mysql://localhost:3306/mxxk?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
       #url: jdbc:mysql://192.168.65.1:3306/mxxk?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
       username: root
       password: root
       driver-class-name: com.mysql.cj.jdbc.Driver
       type: com.alibaba.druid.pool.DruidDataSource
    thymeleaf:
       prefix: classpath:/templates/
       suffix: .html
       mode: HTML
       encoding: UTF-8
       content: text/html
       cache: false
    resources:
      static-locations: classpath:/static/,classpath:/view/,classpath:/public,classpath:/resources,classpath:/META-INF/resources
    mvc:
      static-path-pattern: /static/**
      view:
        prefix: /WEB-INF/jsp/
        suffix: .jsp
#   redis数据库配置
    redis:
        #redis数据库索引 从0开始
       database: 0
      #服务器地址
       host: localhost
      #端口
       port: 6379
      #密码
       password:
       timeout: 3000

#       pool:
#         #连接池最大连接数（使用负值表示没有限制）
#         max-active: 8
#         #连接池最大阻塞等待时间（使用负值表示没有限制）
#         max-wait: -1
#         #连接池中的最大空闲连接
#         max-idle: 8
#         #连接池中的最小空闲连接
#         min-idle: 0

#    mail:
#        host: smtp.qq.com
#        port: 465
#        username: 919071573@qq.com
#        password: rhcmpjiceyodbffe
#        default-encoding: UTF-8
#        properties:
#          mail:
#            smtp:
#              socketFactory:
#                class: javax.net.ssl.SSLSocketFactory
#            debug: true
    mail:
        host: smtp.163.com
        port: 465
        username: mxxk802@163.com
        password: FOGIEUCOHLAWZPOR
        default-encoding: UTF-8
        properties:
          mail:
            smtp:
              socketFactory:
                class: javax.net.ssl.SSLSocketFactory
            debug: true
#       lettuce:
#         pool:
#           max-active: 8
#           max-wait: -1
#           max-idle: 8
#           min-idle: 0

#      jedis:
#        pool:
#          max-active: 8
#          max-idle: 8
#          max-wait: -1
#          min-idle: 0
#    http-client:
#      pool:
#    data:
#      elasticsearch:
#        cluster-nodes: 192.168.220.82:9300
#        local: false
#        repositories:
#          enabled: true






mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.mxxk.lightdream.entity

#httpclients配置
   #最大连接数
#maxTol: 100
#   #并发数
#defaultMaxPerRoute: 20
#   #创建连接的最长时间
#connectTimeout: 20
#   #从连接池中获取到连接的最长时间
#connectionRequestTimeout: 500
#   #数据传输的最长时间
#socketTimeout: 10000
#   #提交请求前测试连接是否可用
#staleConnectionCheckEnabled: true
httpconfig:
    maxTotal: 200
    defaultMaxPerRoute: 20
    connectTimeout: 20000
    connectionRequestTimeout: 20000
    socketTimeout: 20000

##对外接口
apiUrl:
   starUrl: http://localhost:8082
   starToken: 8543C728C4A243EABF191FE4E52BC568

docTemplate:
   stockFreemarkerTemplate: template/stockFreemarkerTemplate.docx
   stockVelocityTemplate: template/stockVelocityTemplate.docx


##系统中反射用到的包名
dirName:
   stockReport: com.mxxk.lightdream.dto.ShareReportModel
   stockBasePackage: com.mxxk.lightdream.dto
   dicEntityPackage: com.mxxk.lightdream.entity.dic

dicNames:
   tableList: dic_stock_type
   dicInit: false










