package com.mxxk.lightdream.entity.dic;

public class DicArea {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_area.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_area.code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_area.name_zh
     *
     * @mbggenerated
     */
    private String nameZh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_area.name_en
     *
     * @mbggenerated
     */
    private String nameEn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_area.name_jp
     *
     * @mbggenerated
     */
    private String nameJp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_area.dialling_code
     *
     * @mbggenerated
     */
    private String diallingCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_area.postcode
     *
     * @mbggenerated
     */
    private String postcode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_area.id
     *
     * @return the value of dic_area.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_area.id
     *
     * @param id the value for dic_area.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_area.code
     *
     * @return the value of dic_area.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_area.code
     *
     * @param code the value for dic_area.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_area.name_zh
     *
     * @return the value of dic_area.name_zh
     *
     * @mbggenerated
     */
    public String getNameZh() {
        return nameZh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_area.name_zh
     *
     * @param nameZh the value for dic_area.name_zh
     *
     * @mbggenerated
     */
    public void setNameZh(String nameZh) {
        this.nameZh = nameZh == null ? null : nameZh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_area.name_en
     *
     * @return the value of dic_area.name_en
     *
     * @mbggenerated
     */
    public String getNameEn() {
        return nameEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_area.name_en
     *
     * @param nameEn the value for dic_area.name_en
     *
     * @mbggenerated
     */
    public void setNameEn(String nameEn) {
        this.nameEn = nameEn == null ? null : nameEn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_area.name_jp
     *
     * @return the value of dic_area.name_jp
     *
     * @mbggenerated
     */
    public String getNameJp() {
        return nameJp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_area.name_jp
     *
     * @param nameJp the value for dic_area.name_jp
     *
     * @mbggenerated
     */
    public void setNameJp(String nameJp) {
        this.nameJp = nameJp == null ? null : nameJp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_area.dialling_code
     *
     * @return the value of dic_area.dialling_code
     *
     * @mbggenerated
     */
    public String getDiallingCode() {
        return diallingCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_area.dialling_code
     *
     * @param diallingCode the value for dic_area.dialling_code
     *
     * @mbggenerated
     */
    public void setDiallingCode(String diallingCode) {
        this.diallingCode = diallingCode == null ? null : diallingCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_area.postcode
     *
     * @return the value of dic_area.postcode
     *
     * @mbggenerated
     */
    public String getPostcode() {
        return postcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_area.postcode
     *
     * @param postcode the value for dic_area.postcode
     *
     * @mbggenerated
     */
    public void setPostcode(String postcode) {
        this.postcode = postcode == null ? null : postcode.trim();
    }
}