package com.mxxk.lightdream.entity.dic;

public class DicCountry {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_country.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_country.code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_country.name_zh
     *
     * @mbggenerated
     */
    private String nameZh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_country.name_en
     *
     * @mbggenerated
     */
    private String nameEn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_country.name_jp
     *
     * @mbggenerated
     */
    private String nameJp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_country.name_en_all
     *
     * @mbggenerated
     */
    private String nameEnAll;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_country.order
     *
     * @mbggenerated
     */
    private Integer order;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_country.id
     *
     * @return the value of dic_country.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_country.id
     *
     * @param id the value for dic_country.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_country.code
     *
     * @return the value of dic_country.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_country.code
     *
     * @param code the value for dic_country.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_country.name_zh
     *
     * @return the value of dic_country.name_zh
     *
     * @mbggenerated
     */
    public String getNameZh() {
        return nameZh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_country.name_zh
     *
     * @param nameZh the value for dic_country.name_zh
     *
     * @mbggenerated
     */
    public void setNameZh(String nameZh) {
        this.nameZh = nameZh == null ? null : nameZh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_country.name_en
     *
     * @return the value of dic_country.name_en
     *
     * @mbggenerated
     */
    public String getNameEn() {
        return nameEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_country.name_en
     *
     * @param nameEn the value for dic_country.name_en
     *
     * @mbggenerated
     */
    public void setNameEn(String nameEn) {
        this.nameEn = nameEn == null ? null : nameEn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_country.name_jp
     *
     * @return the value of dic_country.name_jp
     *
     * @mbggenerated
     */
    public String getNameJp() {
        return nameJp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_country.name_jp
     *
     * @param nameJp the value for dic_country.name_jp
     *
     * @mbggenerated
     */
    public void setNameJp(String nameJp) {
        this.nameJp = nameJp == null ? null : nameJp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_country.name_en_all
     *
     * @return the value of dic_country.name_en_all
     *
     * @mbggenerated
     */
    public String getNameEnAll() {
        return nameEnAll;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_country.name_en_all
     *
     * @param nameEnAll the value for dic_country.name_en_all
     *
     * @mbggenerated
     */
    public void setNameEnAll(String nameEnAll) {
        this.nameEnAll = nameEnAll == null ? null : nameEnAll.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_country.order
     *
     * @return the value of dic_country.order
     *
     * @mbggenerated
     */
    public Integer getOrder() {
        return order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_country.order
     *
     * @param order the value for dic_country.order
     *
     * @mbggenerated
     */
    public void setOrder(Integer order) {
        this.order = order;
    }
}