package com.mxxk.lightdream.entity.dic;

public class DicEntProperty {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_stock_type.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_stock_type.code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_stock_type.name_zh
     *
     * @mbggenerated
     */
    private String nameZh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_stock_type.name_en
     *
     * @mbggenerated
     */
    private String nameEn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_stock_type.name_ja
     *
     * @mbggenerated
     */
    private String nameJa;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_stock_type.order_num
     *
     * @mbggenerated
     */
    private Integer orderNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_stock_type.id
     *
     * @return the value of dic_stock_type.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_stock_type.id
     *
     * @param id the value for dic_stock_type.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_stock_type.code
     *
     * @return the value of dic_stock_type.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_stock_type.code
     *
     * @param code the value for dic_stock_type.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_stock_type.name_zh
     *
     * @return the value of dic_stock_type.name_zh
     *
     * @mbggenerated
     */
    public String getNameZh() {
        return nameZh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_stock_type.name_zh
     *
     * @param nameZh the value for dic_stock_type.name_zh
     *
     * @mbggenerated
     */
    public void setNameZh(String nameZh) {
        this.nameZh = nameZh == null ? null : nameZh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_stock_type.name_en
     *
     * @return the value of dic_stock_type.name_en
     *
     * @mbggenerated
     */
    public String getNameEn() {
        return nameEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_stock_type.name_en
     *
     * @param nameEn the value for dic_stock_type.name_en
     *
     * @mbggenerated
     */
    public void setNameEn(String nameEn) {
        this.nameEn = nameEn == null ? null : nameEn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_stock_type.name_ja
     *
     * @return the value of dic_stock_type.name_ja
     *
     * @mbggenerated
     */
    public String getNameJa() {
        return nameJa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_stock_type.name_ja
     *
     * @param nameJa the value for dic_stock_type.name_ja
     *
     * @mbggenerated
     */
    public void setNameJa(String nameJa) {
        this.nameJa = nameJa == null ? null : nameJa.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_stock_type.order_num
     *
     * @return the value of dic_stock_type.order_num
     *
     * @mbggenerated
     */
    public Integer getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_stock_type.order_num
     *
     * @param orderNum the value for dic_stock_type.order_num
     *
     * @mbggenerated
     */
    public void setOrderNum(Integer orderNum) {
        this.orderNum = orderNum;
    }
}