package com.mxxk.lightdream.entity.dic;

/**
 * SystemDictTableEntity
 *
 * @auther zhang
 * @date 2020/6/6
 **/

public class SystemDictTableEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_area.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_area.code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_area.name_zh
     *
     * @mbggenerated
     */
    private String nameZh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_area.name_en
     *
     * @mbggenerated
     */
    private String nameEn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_area.name_jp
     *
     * @mbggenerated
     */
    private String nameJa;



    private Integer orderNum;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getNameZh() {
        return nameZh;
    }

    public void setNameZh(String nameZh) {
        this.nameZh = nameZh;
    }

    public String getNameEn() {
        return nameEn;
    }

    public void setNameEn(String nameEn) {
        this.nameEn = nameEn;
    }



    public Integer getOrderNum() {
        return orderNum;
    }

    public void setOrderNum(Integer orderNum) {
        this.orderNum = orderNum;
    }

    public String getNameJa() {
        return nameJa;
    }

    public void setNameJa(String nameJa) {
        this.nameJa = nameJa;
    }

    @Override
    public String toString() {
        return "SystemDictTableEntity{" +
                "id=" + id +
                ", code='" + code + '\'' +
                ", nameZh='" + nameZh + '\'' +
                ", nameEn='" + nameEn + '\'' +
                ", nameJa='" + nameJa + '\'' +
                ", orderNum=" + orderNum +
                '}';
    }
}
