package com.mxxk.lightdream.mapper;


import com.mxxk.lightdream.entity.Shares;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

import java.util.List;

@Mapper
@Repository
public interface SharesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shares
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shares
     *
     * @mbggenerated
     */
    int insert(Shares record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shares
     *
     * @mbggenerated
     */
    int insertSelective(Shares record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shares
     *
     * @mbggenerated
     */
    Shares selectByPrimaryKey(Integer id);

    Shares selectByStockcode(String stockCode);

    List<Shares> selectAllShares();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shares
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Shares record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shares
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Shares record);
}