package com.mxxk.lightdream.mapper;


import com.mxxk.lightdream.entity.TradeData;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface TradeDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_data
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_data
     *
     * @mbggenerated
     */
    int insert(TradeData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_data
     *
     * @mbggenerated
     */
    int insertSelective(TradeData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_data
     *
     * @mbggenerated
     */
    TradeData selectByPrimaryKey(Long id);

    TradeData selectByStockCode(String stockCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_data
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TradeData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_data
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(TradeData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_data
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TradeData record);


    int updateByStockCode(TradeData record);
}